version: '3.1'

services:
  # dev-only
  mysql:
    container_name: discord_bot_mysql
    restart: always
    image: mysql:8.0.4
    environment:
      MYSQL_DATABASE: discord_database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
