version: '3.1'

services:
  # dev-only
  mysql:
    container_name: discord_bot_mysql
    restart: always
    image: mysql
    environment:
      MYSQL_DATABASE: discord_database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
