packages:
  - '!**/dist/**'
  - '!**/tmp/**'
  - '!**/node_modules/**'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - canvas
  - core-js
  - esbuild
  - nx
  - prisma
  - unrs-resolver
