import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  await prisma.cardType.createMany({
    data: [
      {
        id: 1,
        name: 'Madeleines',
        description: 'Madeleines de Contres dans le 41',
        level: 2,
        imageName: 'madeleines.jpg',
        isFusion: 0,
        lore: 'Ces fameuses madeleines étaient le petit encas phare lors de stream. Pour parodier les placements de produits de vos Youtubers favoris, je me suis amusé à lire le dos du paquet, et les fameuses madeleines de Contres dans le 41 sont devenus un running ...',
      },
      {
        id: 2,
        name: "Maurice, l'irradié",
        description: 'Le Maurice originel',
        level: 3,
        imageName: 'maurice-fallout.jpg',
        isFusion: 0,
        lore: "Lors du Let's Play de Fallout 4, après avoir demandé au chat un prénom, c'est le doux nom de Maurice qui est sorti. Plutot que de faire un personnage joli comme la plupart des gens, il a été décidé de faire un personnage moche. Maurice est né.",
      },
      {
        id: 3,
        name: 'Maurice, le revenant',
        description: "Rien n'est difficile pour Maurice",
        level: 1,
        imageName: 'maurice-souls.jpg',
        isFusion: 0,
        lore: "Dark Souls 3 a été le jeu suivant Fallout 4 où il y a eu une création de personnage. Un petit rituel est né, à faire un personnage moche, et qui s'appelle Maurice.",
      },
      {
        id: 4,
        name: 'Maurice, le sanguinaire',
        description: "C'est le sang",
        level: 1,
        imageName: 'maurice-born.jpg',
        isFusion: 0,
        lore: 'A la suite de Dark Souls 3, un nouveau Maurice est né en le créant pour Bloodborne. Après un personnage irradié et un revenant, il est devenu un chasseur de sang.',
      },
      {
        id: 5,
        name: 'Maurice, le ninja',
        description: 'Un voleur reconverti',
        level: 1,
        imageName: 'maurice-ff1.jpg',
        isFusion: 0,
        lore: "Le marathon Final Fantasy commença par le premier opus où l'on peut nommer 4 personnages. Il fallait donc forcément un personnage appelé Maurice, et c'est le voleur devenu ninja qui a eu cette chance.",
      },
      {
        id: 6,
        name: "Maurice, l'idiot bête",
        description: "L'ami des castors",
        level: 1,
        imageName: 'maurice-ff2.jpg',
        isFusion: 0,
        lore: "Final Fantasy II permet de renommer tous les personnages comme le premier opus, mais contrairement au premier jeu, chaque personnage a une vraie personnalité. L'idiot du village (et qui sait parler aux castors) était tout désigné pour s'appeler Mauri...",
      },
      {
        id: 7,
        name: 'Maurice, le sauveur',
        description: 'Ses soins ont sauvé le monde des ténèbres',
        level: 2,
        imageName: 'maurice-ff3.jpg',
        isFusion: 0,
        lore: "Dans le 3eme Final Fantasy, c'est le personnage tout timide et chétif qui a été nommé Maurice. Il était soigneur et il a été le sauveur de l'équipe lors du combat final.",
      },
      {
        id: 8,
        name: 'Maurice, le sauvage',
        description: "I'm Gau ! I your friend...FRIEND !",
        level: 1,
        imageName: 'maurice-ff6.jpg',
        isFusion: 0,
        lore: "Final Fantasy VI possède un personnage sauvage et qui ne sait pas trop s'exprimer, un peu comme pour Final Fantasy II. Il était forcément parfait pour devenir un Maurice de cette longue lignée.",
      },
      {
        id: 9,
        name: 'Mauricette',
        description: 'ça aurait pu être un chien',
        level: 1,
        imageName: 'maurice-ff8.jpg',
        isFusion: 0,
        lore: "Final Fantasy VIII était un jeu particulier. Là où d'ordinaire c'est Zell qui aurait dû être un Maurice (vu qu'il est un peu débile), il était amusant d'appeler Linoa Mauricette, et de nommer son chien Linoa. Parce qu'on aime l'humour ici.",
      },
      {
        id: 10,
        name: 'Maurice, le poney',
        description: 'La foudre incarnée',
        level: 1,
        imageName: 'maurice-ff10.jpg',
        isFusion: 0,
        lore: "Le dixième opus ne permet pas de renommer ses personnages, cependant il est possible de le faire pour les invocations. A choisir parmi toutes les invocations, un poney était le plus adéquate (même s'il est beau comparé aux Maurices)",
      },
      {
        id: 11,
        name: 'Maurice, le weaboo',
        description: 'Il a plus de queues que Naruto',
        level: 2,
        imageName: 'maurice-code-vein.jpg',
        isFusion: 0,
        lore: 'Nouveau jeu proche des premiers jeux où Maurice apparaissait, Code Vein propose un éditeur de personnage très riche, de quoi faire une immondice digne de ce nom. Avec son style manga, Maurice est devenu un vrai weeb.',
      },
      {
        id: 12,
        name: 'Exodia le Maurice',
        description: "La plus grande beauté de l'univers",
        level: 3,
        imageName: 'maurice-exodia.jpg',
        isFusion: 1,
        lore: 'Fusion de toutes ces légendes, vous aurez surement reconnu la référence à Exodia le maudit.',
      },
      {
        id: 13,
        name: "Largage de croiss'",
        description: "Un meilleur largage tactique que dans n'importe quel COD",
        level: 1,
        imageName: 'gartic-croissant.jpg',
        isFusion: 0,
        lore: 'Lors de nos soirées Gartic Phone, on a eu le droit à un dessin de largage de croissant tactique qui nous a fait mourir de rire de par cette réalisation graphique incroyable.',
      },
      {
        id: 14,
        name: "L'éléphant d'Ystaroth",
        description:
          '"Tout le monde a reconnu l\'éléphant donc mon dessin est valide quand même !"',
        level: 1,
        imageName: 'gartic-elephant.jpg',
        isFusion: 0,
        lore: 'Ystaroth, ce dessinateur émérite, nous a valu un éléphant de qualité, ainsi que la petite citation que vous pouvez voir sous la carte.',
      },
      {
        id: 15,
        name: 'La centrale de Tchernobyl',
        description: "C'est pas en Russie bordel !",
        level: 1,
        imageName: 'gartic-tchernobyl.jpg',
        isFusion: 0,
        lore: 'Dessin devenu assez régulier, il y avait une certaine facination pour la Russie et la centrale de Tchernobyl. Ne me demandez pas pourquoi.',
      },
      {
        id: 16,
        name: 'Le talent de Sashalex',
        description: '"Un éminent artiste du mouvement de la souris pour sure"',
        level: 1,
        imageName: 'sasha-talent.jpg',
        isFusion: 0,
        lore: 'Comme vous pouvez le voir avec les cartes sur Gartic Phone, nous avons beaucoup de talent au dessin, mais Sasha est tout particulièrement un artiste de renom. Le nouveau Monet.',
      },
      {
        id: 17,
        name: 'Lund, le warlord',
        description: 'Le maître de ces lieux',
        level: 4,
        imageName: 'lund.jpg',
        isFusion: 0,
        lore: "C'est moi. Cet avatar est un avatar que j'ai longtemps gardé, c'est Biance de Dragon Quest, en particulier du film dispo sur Netflix (regardez le)",
      },
      {
        id: 18,
        name: 'Ystaroth, le copilote',
        description: "Ringfiteur de l'extreme",
        level: 4,
        imageName: 'ystaroth.jpg',
        isFusion: 0,
        lore: 'Ystaroth, le bro, copilote du stream, le partenaire de jeux coopératifs, une vraie machine de muscle.',
      },
      {
        id: 19,
        name: 'Vesperia, le libéro',
        description: 'Ze binedigue of Isaac',
        level: 3,
        imageName: 'vesperia.jpg',
        isFusion: 0,
        lore: 'Avec Vesperia, nous nous connaissons depuis ConsoleFun où nous avions une chronique où il avait dit mal prononcé le nom "The binding of Isaac". On a aussi eu un sombre délire sur Rocket League avec Barthez, comme quoi il était libéro et remontait l...',
      },
      {
        id: 20,
        name: 'Equinoxe, le chateux',
        description: "Mass Effect 2 c'est de la merde",
        level: 3,
        imageName: 'equinoxe.jpg',
        isFusion: 0,
        lore: "Equinoxe est bien connu pour avoir le cul bordé de nouilles, et d'aimer la saga Mass Effect à part le second opus.",
      },
      {
        id: 21,
        name: 'Dramo, le lobbyiste',
        description: 'ANTHEM, BIOWARE, XBOX, CYBERPUNK',
        level: 3,
        imageName: 'dramo.jpg',
        isFusion: 0,
        lore: 'Dramo a la facheuse tendance à prendre parti, un peu aveuglément de temps en temps. Il est fan de Bioware (Anthem, Mass Effect) et de Xbox, et avait défendu ardemment Cyberpunk (pour aucune raison).',
      },
      {
        id: 22,
        name: 'Ashara, le disparu',
        description: "On pense que Dramo l'a assassiné",
        level: 1,
        imageName: 'ashara.jpg',
        isFusion: 0,
        lore: "Ashara a disparu pendant un peu plus d'un an. Dramo avait pour résolution, la même année, de l'assassiner. On a longtemps cru qu'il était le tueur mais Ashara est revenu parmi nous.",
      },
      {
        id: 23,
        name: 'Groudon, le fanboy',
        description: 'Fan invétéré de FFXIII',
        level: 1,
        imageName: 'groudon.jpg',
        isFusion: 0,
        lore: "Groudon a suivi le marathon en fervant défenseur de Final Fantasy. Il est très fan de Final Fantasy XIII et je pense que l'entiéreté de la planète est au courant.",
      },
      {
        id: 24,
        name: 'Hirkillion, le bourrin',
        description: "Aussi subtil qu'une masse",
        level: 2,
        imageName: 'hirkillion.jpg',
        isFusion: 0,
        lore: "Hirkillion est une personne peu subtile, il est un peu bourrin, et ses personnages sur Borderlands le prouve bien. Mais on l'aime bien quand même.",
      },
      {
        id: 25,
        name: 'Khara, le toxique',
        description: 'Aussi appelé Foxy mini gamer',
        level: 1,
        imageName: 'khara.jpg',
        isFusion: 0,
        lore: 'Khara, fut un temps, avait pour pseudo FoxyMG (pour Foxy Mélée générale). On a peut être un peu déformé son pseudo. Mais il est toxique car joueur de LoL, donc on a le droit.',
      },
      {
        id: 26,
        name: 'xPlayLivex',
        description: 'LundProd, les origines',
        level: 1,
        imageName: 'xplaylivex.jpg',
        isFusion: 0,
        lore: "A l'origine, la chaine s'appelait xPlayLivex. Une triste erreur de jeunesse. Don't judge me.",
      },
      {
        id: 27,
        name: 'La badoit rouge de Lund',
        description: "L'eau des véritables bulles-dozers",
        level: 1,
        imageName: 'lund-badoit.jpg',
        isFusion: 0,
        lore: "Grand fan de Badoit Rouge, c'est la boisson sponsor lors des streams. Enfin si j'avais un quelconque partenariat.",
      },
      {
        id: 28,
        name: 'Bande de petite pute',
        description: "Vous pouvez m'aider pour un hack CSGO ?",
        level: 1,
        imageName: 'petite-pute.jpg',
        isFusion: 0,
        lore: "C'est l'histoire d'un personnage un peu particulier du nom de Yatsuo. Il apprenait à développer, était un peu bizarre, et il voulait devenir modo. Un jour il a demandé si on pouvait l'aider à dev un cheat pour CSGO, pour \"s'amuser\" et \"boost les bre...",
      },
      {
        id: 29,
        name: 'Le faux espoir de Dramo',
        description: 'Il aura un nouveau PC un jour... un jour',
        level: 2,
        imageName: 'dramo-pc.jpg',
        isFusion: 0,
        lore: "Il était une fois un ordinateur, qui a cramé. Dramo, son possesseur, a plusieurs fois parlé d'en racheter un, qu'il ferait tel ou tel jeu quand il aura un nouveau PC........ On l'attend encore",
      },
      {
        id: 30,
        name: 'Les stères de bois de Vesperia',
        description: 'Saviez vous que 4 stères équivalent à 1 corde ?',
        level: 1,
        imageName: 'vesperia-stere.jpg',
        isFusion: 0,
        lore: "Vesperia s'ennuyait, et s'est retrouvé sur un site de conversion d'unité. En premier c'était pour convertir des devises de monnaie, mais le site proposait aussi des conversions de mesure de bois. Il est alors devenu l'expert dans ce domaine, traduisan...",
      },
      {
        id: 31,
        name: 'Les FDP',
        description:
          "Les forces de défense de Poudlard. On raconte qu'une mangouste est à leur tête",
        level: 1,
        imageName: 'fdp.jpg',
        isFusion: 0,
        lore: 'Avec Vesperia (encore), nous jouions beaucoup à Rocket League, et nous avons créé notre club pour avoir nos couleurs personnalisées. Parce que nous sommes de petits plaisantins, nous nous sommes appelés les Forces de Défense de Poudlard, pour avoir...',
      },
      {
        id: 32,
        name: "La défense, c'est ma passion",
        description: "La meilleure des défenses, c'est la défense",
        level: 1,
        imageName: 'battleborn.jpg',
        isFusion: 0,
        lore: "Jeu fait en coop avec Ysta et Vesperia, Battleborn était très sympathique. Du moins au début, parce qu'au bout d'un moment, quand les missions ne devenaient plus que des défenses de points, le jeu devenait répétitif, et nous avons habilement ironis...",
      },
      {
        id: 33,
        name: 'Le programme télé de Dramo',
        description: 'Salut mes petites chéries',
        level: 1,
        imageName: 'dramo-hanouna.jpg',
        isFusion: 0,
        lore: "Dramo adore TMTP jusqu'à défendre corps et ame l'émission (comme chaque truc qu'il aime). On l'aime bien quand même malgré ses erreurs de jeunesse.",
      },
      {
        id: 34,
        name: 'Monaco & Blackguard',
        description: 'Tout le monde les déteste, sauf Dronfax',
        level: 1,
        imageName: 'monaco-blackguard.jpg',
        isFusion: 0,
        lore: "Lorsque j'étais chez ConsoleFun, j'ai eu l'occasion de tester Blackguards 1 et de jouer avec Vesperia à Monaco. Dans les 2 cas, le ragequit a été rapide parce que les jeux étaient pas fous. Mais Dronfax a apprécié Blackguard 2 et a dit que Monaco ...",
      },
      {
        id: 35,
        name: 'Falagar',
        description: 'Suivez moi',
        level: 1,
        imageName: 'falagar.jpg',
        isFusion: 0,
        lore: 'Falagar est un personnage du jeu Might And Magic VI : Le mandat Céleste. Ce très vieux jeu nous a marqué Ystaroth et moi pour sa cinématique d\'intro où un vieux apparait, un des personnages dit : "Falagar !" et il répond "Suivez moi". J\'ai jamais f...',
      },
      {
        id: 36,
        name: "L'eurovision",
        description: 'Toujours présent, toujours déçu',
        level: 1,
        imageName: 'eurovision.jpg',
        isFusion: 0,
        lore: "L'eurovision est un rendez vous annuel que je suis avec Ysta, un moment sacré. Les 2 fois où nous l'avons streamé, les 2 fois nous avons entendu des candidats en disant : \"Lui/elle n'a aucune chance\". C'est eux qui ont gagné.",
      },
      {
        id: 37,
        name: "Le sommeil d'Ysta",
        description: "S'endort pour les streams, même ceux qu'il doit faire",
        level: 1,
        imageName: 'ystaroth-sleeper.jpg',
        isFusion: 0,
        lore: 'Des fois, des streams étaient prévus avec Ystaroth. Des fois, il faisait un petit somme avant de venir en stream. Des fois, il ne se réveillait pas.',
      },
      {
        id: 38,
        name: 'Les streams avant 2016',
        description: "Les streams que vous n'avez jamais vu",
        level: 1,
        imageName: 'old-live.jpg',
        isFusion: 0,
        lore: "Avant l'été 2016 où j'ai vraiment commencé à streams fréquemment, j'avais déjà fait quelques streams et notamment l'entièreté du jeu Forced avec Ystaroth. Des streams dont personne n'est au courant, que personne n'a vu. Il paraitrait que des re...",
      },
      {
        id: 39,
        name: 'Jeff Tuches',
        description: 'Une carte, ok, mais pas 15 ?!',
        level: 1,
        imageName: 'jeff-tuche.jpg',
        isFusion: 0,
        lore: "Grand fan de comédie Française, j'adore les Tuches. Cela fait débat, mais après tout, les plus grands génies sont souvent incompris.",
      },
      {
        id: 40,
        name: 'Ouvrez moi !',
        description: 'Meow Meow',
        level: 1,
        imageName: 'equinoxe-chats.jpg',
        isFusion: 0,
        lore: "Running gag quand un stream se déroulait avec Equinoxe, ses chats avaient l'habitude de gratter à la porte pour vouloir sortir ou rentrer. C'est vraiment l'un de ses chats sur la carte.",
      },
      {
        id: 41,
        name: 'Il est taquin !',
        description:
          "Sasha a les bases de l'humour, on espère qu'il aura celles du français un jour",
        level: 1,
        imageName: 'sasha-humour.jpg',
        isFusion: 0,
        lore: "Sasha est un petit blagueur, il a notamment plus d'une fois tenté des jeux de mots ou des blagues audacieuses. Parfois réussies. Parfois.",
      },
      {
        id: 42,
        name: 'Le tchou tchou shoe',
        description: 'Chaga Chaga Chaga, Chaga Chaga Chaga, Tchou tchou !',
        level: 2,
        imageName: 'choo-choo-shoe.jpg',
        isFusion: 0,
        lore: "Charlie the unicorn est une série sur Youtube un peu décalée. On peut y retrouver notamment la fameuse Tchou Tchou Shoe, une chaussure train, qui a servi d'écran de chargement notamment lors des aventures dans FFXIII.",
      },
      {
        id: 43,
        name: 'Sergent Pepper',
        description: 'This is the law',
        level: 1,
        imageName: 'sergent-pepper.jpg',
        isFusion: 0,
        lore: "Le Sergent Pepper est arrivé sur la chaine en même temps que Charlie The Unicorn, à l'époque où on finissait les streams avec des vidéos marrantes. Si vous avez FrankerFaceZ, il est aussi possible de voir une émote à son effigie sur le stream.",
      },
      {
        id: 44,
        name: 'AZZA Paladins',
        description: '2 saisons de try-hard',
        level: 2,
        imageName: 'azza.jpg',
        isFusion: 0,
        lore: "L'AZZA était un concept simple qui a été réalisé 2 fois avec Equinoxe sur Paladins : Je commence avec le premier personnage dans l'ordre alphabétique, lui le dernier personnage, et nous essayons de gagner avec ce duo. Si on gagne, on avance d'un pe...",
      },
      {
        id: 45,
        name: 'Warframe Cards',
        description: 'Promis, ça viendra un jour',
        level: 1,
        imageName: 'warframe-cards.jpg',
        isFusion: 0,
        lore: "Warframe Cards était un projet de fangame. Il arrivera un jour, c'est sûr.",
      },
      {
        id: 46,
        name: 'La vidéo lore Warframe',
        description: 'Promis, ça viendra un jour',
        level: 1,
        imageName: 'lore-warframe.jpg',
        isFusion: 0,
        lore: "Une vidéo résumant le lore de Warframe est un projet que j'ai et qui arrivera un jour. Il faut juste avant que je fasse un progress sur chaque quête du jeu. Mais ça arrivera un jour, c'est sûr.",
      },
      {
        id: 47,
        name: 'La suite de Breath of Fire 3',
        description: 'Promis, ça viendra un jour, hein Ysta ?',
        level: 1,
        imageName: 'ystaroth-bof.jpg',
        isFusion: 0,
        lore: "Ystaroth avait streamé un peu sur ma chaine, et il avait commencé Breath of Fire 3. On a jamais eu la suite. Mais ça arrivera un jour, n'est ce pas Ysta ?",
      },
      {
        id: 48,
        name: 'Livedeck',
        description: "Il fut un temps où l'idée était bonne",
        level: 1,
        imageName: 'touch-portal.jpg',
        isFusion: 0,
        lore: "Livedeck était un projet que j'avais pour éviter de payer très cher un streamdeck mais avec les mêmes possibilités. Au final, Touch Portal est une solution qui permet déjà tout ça. Pas besoin de réinventer la roue.",
      },
      {
        id: 49,
        name: 'Exploration de steam',
        description: "Gaben a fait pression pour qu'on arrête",
        level: 2,
        imageName: 'exploration-steam.jpg',
        isFusion: 0,
        lore: "L'Exploration de Steam était une émission hebdomadaire où nous testions avec Ysta un jeu Free To Play sur Steam, avec une petite note à la fin de notre part mais aussi du chat.",
      },
      {
        id: 50,
        name: 'Flashback',
        description: "L'histoire d'une autre époque",
        level: 2,
        imageName: 'flashback.jpg',
        isFusion: 0,
        lore: 'Flashback était un concept où je passais 1h/1h30 sur un jeu de mon enfance pour le faire découvrir et voir si la nostalgie altérait mes souvenirs. Des fois oui, des fois non.',
      },
      {
        id: 51,
        name: 'Les choix humble',
        description: "Vous n'aurez plus de jeux offerts",
        level: 2,
        imageName: 'humble-choice.jpg',
        isFusion: 0,
        lore: 'Les choix humbles (précédemment appelés "Les mois humbles") étaient une émission où je testais une partie des jeux dispos dans le Humble Choice (précédemment appelés Humble Monthly) et où je donnais mon avis sur les jeux/sur le bundle pour voir...',
      },
      {
        id: 52,
        name: 'Randomframe',
        description: "Parce qu'il n'y a pas assez d'aléatoire dans Warframe",
        level: 2,
        imageName: 'randomframe.jpg',
        isFusion: 0,
        lore: 'Randomframe était une émission où nous jouions tous les missions de Warframe avec un stuff aléatoire et des gages. Ce fut long, parfois compliqué, mais marrant.',
      },
      {
        id: 53,
        name: 'Nouvel an sous la pluie',
        description: 'Commencé en coop, terminé en solo',
        level: 1,
        imageName: 'risk-of-rain.jpg',
        isFusion: 0,
        lore: "Lors d'un stream de nouvel an, j'ai joué à Risk of Rain avec Vesperia. Si tout le long du jeu, j'étais nul et je mourrais tout le temps, c'est lors du boss de fin que Vesperia est mort et que j'ai vaincu le boss tout seul. Un grand moment de g@ming.",
      },
      {
        id: 54,
        name: 'Rattrapage in-extremis',
        description: 'Le coude dans le foie gras et le jambon',
        level: 1,
        imageName: 'nouvel-an.jpg',
        isFusion: 0,
        lore: "Lors d'un stream de Noel avec Ystaroth, on a fait un live cuisine. Mon coude a failli renverser des papillotes de jambon cru et de foie gras, mais un habile mouvement digne des plus grands gymnastes a permis d'éviter la catastrophe.",
      },
      {
        id: 55,
        name: 'Top 1 sur Realm Royale',
        description: 'Il est mort trop jeune',
        level: 1,
        imageName: 'realm-royale.jpg',
        isFusion: 0,
        lore: "Realm Royale a été le seul BR où je me suis investi, accompagné majoritairement d'Equinoxe. On a fait de multiples top 1, mais le jeu a disparu aussi vite qu'il est apparu.",
      },
      {
        id: 56,
        name: 'Le fuckboy',
        description: 'Louis, le gars sûr',
        level: 2,
        imageName: 'louis-code-vein.jpg',
        isFusion: 0,
        lore: "Allié choisi lors de mon aventure sur Code Vein, Louis est le bro qui m'a ressucité un bon nombre de fois au dépend de sa propre vie. Merci Louis.",
      },
      {
        id: 57,
        name: 'Puff Puff',
        description: 'Jessica et Jade peuvent le faire. Les gluants aussi',
        level: 1,
        imageName: 'puff-puff.jpg',
        isFusion: 0,
        lore: "Le puff puff est une référence graveleuse présente dans la plupart des jeux Dragon Quest, et les waifus que sont Jessica (DQ8) et Jade (DQ11) n'ont pas laissées indifférents certains viewers qui auraient bien aimé un puff puff de leur part.",
      },
      {
        id: 58,
        name: "L'exploit' des lasers",
        description: 'Quand le chat veut ta mort',
        level: 1,
        imageName: 'clustertruck.jpg',
        isFusion: 0,
        lore: "Clustertruck est l'un des rares jeux faits avec l'intégration Twitch, où les viewers pouvaient voter pour un malus. Le plus redoutable était les lasers à l'arrière de chaque camion. Sauf que le problème, c'est que les viewers ont vite compris comme...",
      },
      {
        id: 59,
        name: 'Encore une quête',
        description:
          'Une petite quête secondaire et après on fait la quête principale, promis',
        level: 2,
        imageName: 'quete-annexe.jpg',
        isFusion: 0,
        lore: "Fan de RPG, j'ai un peu la sale manie de faire un maximum de quêtes. FFXV fut notamment le moment où une quête secondaire en suivait une autre, et la quête principale devenait un lointain souvenir.",
      },
      {
        id: 60,
        name: 'ConsoleFun',
        description: "C'était pas si fun",
        level: 1,
        imageName: 'console-fun.jpg',
        isFusion: 0,
        lore: "ConsoleFun a été un site sur lequel j'ai oeuvré plusieurs années durant, et même si j'y ai fait de bonnes rencontres, ce n'était pas forcément une expérience très intéressante pour mon expérience de vidéaste.",
      },
      {
        id: 61,
        name: 'Les Lund & Troyer',
        description: "Y'en a un qui est plus drole que l'autre",
        level: 1,
        imageName: 'lund-troyer.jpg',
        isFusion: 0,
        lore: "Les Lund & Troyer étaient une série de petits challenges faits sur des jeux choisis chacun notre tour, condensés en petits best of et avec un compte de points d'épisode en épisode. Un contenu qui a vieilli mais qui je pense peut encore se regarder d...",
      },
      {
        id: 62,
        name: 'Les best-of Lund & Ysta',
        description: 'Le duo préféré des Français',
        level: 3,
        imageName: 'best-of.jpg',
        isFusion: 0,
        lore: 'Les best of, ces résumés de moment de coopération avec Ysta, remplis de fun et de moments de gameplay incroyables. Surement mon type de contenu préféré sur la chaine.',
      },
      {
        id: 63,
        name: 'MauriceBot',
        description:
          'Il a plus de chance de planter que de mettre la balle dans le filet',
        level: 3,
        imageName: 'maurice-bot.jpg',
        isFusion: 1,
        lore: 'Votre humble serviteur, votre interlocuteur lorsque vous jouez au gacha, et votre partenaire officiel de tennis de table.',
      },
      {
        id: 64,
        name: 'Ok I believe you',
        description: 'Parce les héros de RPG sont crédules',
        level: 2,
        imageName: 'kh-believe.jpg',
        isFusion: 0,
        lore: 'Meme dans la communauté Kingdom Hearts, cette phrase issu de KH Birth By Sleep a été reprise par Just A Pancake pour montrer la crédulité des héros de JRPG.',
      },
      {
        id: 65,
        name: 'Darkness',
        description: 'Darkness, darkness, darkness',
        level: 1,
        imageName: 'kh-darkness.jpg',
        isFusion: 0,
        lore: "Ansem est un personnage un peu attiré par les ténèbres. C'est donc l'une des uniques choses qu'il sait dire dans les vidéos de Just A Pancake. Encore un meme.",
      },
      {
        id: 66,
        name: 'Does not compute',
        description: 'System shutdown',
        level: 1,
        imageName: 'kh-compute.jpg',
        isFusion: 0,
        lore: 'Dans KH Chain of Memories, la réplique de Riku "bug". Notre fameux Just A Pancake a alors sorti cette phrase "Does not compute, does not compute, System shutdown" lorsqu\'il tombe. C\'était rigolo et je l\'ai repris en alerte de sub quand je faisais du KH.',
      },
      {
        id: 67,
        name: 'Demyx le gros cerveau',
        description: 'Il tirait les ficelles depuis le début',
        level: 1,
        imageName: 'kh-mom-demyx.jpg',
        isFusion: 0,
        lore: "Une théorie tordue de la part de certains fans et qu'Equinoxe voudrait réelle est que Demyx serait le maitre des maitres. Hautement improbable, cette théorie est drole car Demyx est un comic relief qui ne sert pas à grand chose.",
      },
      {
        id: 68,
        name: "C'est qui cette waifu ?",
        description: 'Oubliée de tous',
        level: 2,
        imageName: 'kh-xion.jpg',
        isFusion: 0,
        lore: 'Xion est un de mes personnages préférés, mais qui est oubliée de tous à un moment (je ne vais pas vous spoiler). Vous comprenez mieux le nom de la carte.',
      },
      {
        id: 69,
        name: 'La meilleure waifu',
        description: "Mickey... you're too late",
        level: 2,
        imageName: 'kh-aqua.jpg',
        isFusion: 0,
        lore: "Une autre de mes waifus, Aqua, qui a une vie un peu merdique mais qui pète la classe. La description de sa carte est une citation du personnage lors d'un moment incroyable qui m'a un peu mis en PLS, mais tranquille.",
      },
      {
        id: 70,
        name: "Les glaces à l'eau de mer",
        description: 'En vrai ça doit etre immonde',
        level: 1,
        imageName: 'kh-glace.jpg',
        isFusion: 0,
        lore: "Dans KH 358/2 days, les personnages mangent souvent des glaces à l'eau de mer. Si d'après certains qui ont reproduits la recette c'est ok, je me dis que ça doit être immonde.",
      },
      {
        id: 71,
        name: 'KEYBLADE',
        description: 'KEYBLADE KEYBLADE KEYBLADE',
        level: 1,
        imageName: 'kh-keyblade-xehanort.jpg',
        isFusion: 0,
        lore: "Dernière carte avec un meme issu des vidéos de Just a Pancake, c'est notre méchant préféré, Xehanort, qui dans ses vidéos dit juste \"Keyblade\" mais est sous titré avec des vraies phrases. Parce que c'est vrai qu'il a un léger problème avec la K...",
      },
      {
        id: 72,
        name: 'Une histoire compliquée',
        description:
          'Des mondes de lumière, de ténèbres, des voyages dans le temps...',
        level: 2,
        imageName: 'kh-nomura.jpg',
        isFusion: 1,
        lore: "Testuya Nomura est un créateur avec beaucoup d'imagination, peut être trop. Il est cependant l'auteur d'une licence atypique à succès qu'on m'a longtemps vendu et dans laquelle je suis tombée.",
      },
      {
        id: 73,
        name: 'FFI - Samu le mage blanc',
        description: 'Faut pas demander son 06, mais son 15',
        level: 2,
        imageName: 'ff1-samu.jpg',
        isFusion: 0,
        lore: "Premier épisode du Marathon, en plus d'avoir un Maurice dans l'équipe, il y avait un mage blanc. Grace à un trait d'esprit emplie d'un humour décapant, ce personnage a été appelé \"Samu\".",
      },
      {
        id: 74,
        name: 'FFII - La magie ultime',
        description: 'Ultima, le pire sort du jeu vendu comme le plus puissant',
        level: 1,
        imageName: 'ff2-ultima.jpg',
        isFusion: 0,
        lore: "Ultima est soit disant la magie la plus puissante dans l'univers de FFII. Problème, le gameplay et une erreur dans le code du jeu fait qu'une fois acquise, cette magie est une déception de A à Z.",
      },
      {
        id: 75,
        name: 'FFIII - Garuda, le pire boss',
        description: 'Obligé de jouer chevalier noir, ça dégoute',
        level: 1,
        imageName: 'ff3-garuda.jpg',
        isFusion: 0,
        lore: "Final Fantasy III possède un système de job, mais le boss Garuda oblige a utilisé une certaine classe, ce qui ne me faisait pas plaisir. J'ai longtemps essayé de tuer le boss avec mon équipe originelle, mais rien à faire.",
      },
      {
        id: 76,
        name: "FFIV - Edward l'infirme",
        description: "Toujours à l'hosto, jamais utile",
        level: 3,
        imageName: 'ff4-edward.jpg',
        isFusion: 0,
        lore: "Final Fantasy IV possède plusieurs héros charismatique, cependant l'un deux est une victime doublé d'un incapable. Il finit à un moment à l'hopital, ce qui correspond bien au personnage.",
      },
      {
        id: 77,
        name: 'FFV - La bonne surprise',
        description: 'Gilgamesh le side kick rigolo',
        level: 3,
        imageName: 'ff5-gilgamesh.jpg',
        isFusion: 0,
        lore: "L'un des ennemis les plus marquant de FFV est Gilgamesh. Tellement marquant qu'il fait des caméos dans d'autres jeux de la série. Ayant pour role de side kick rigolo, il permet d'adoucir des situations pourtant très grave dans le scénario. Ce cinqui...",
      },
      {
        id: 78,
        name: 'FFVI - Inconnus au bataillon',
        description:
          "Des compagnons optionnels qui n'ont jamais eu la chance d'être récupérés",
        level: 2,
        imageName: 'ff6-mog-gogo-omaru.jpg',
        isFusion: 0,
        lore: "Final Fantasy VI possède BEAUCOUP de personnages, dont certains très optionnels, si bien que je n'ai jamais récupéré Mog, Umaro et Gogo.",
      },
      {
        id: 79,
        name: 'FFVII - Les serpillères volantes',
        description: 'Elles servent à dépoussiérer le jeu original',
        level: 4,
        imageName: 'ff7-whispers.jpg',
        isFusion: 0,
        lore: 'Final Fantasy VII Remake possède des petites différences par rapport au jeu principal, et notamment on peut apercevoir plusieurs fois dans le jeu des espèces de fantomes, qui ressemblent à des serpillères volantes.',
      },
      {
        id: 80,
        name: 'FFVIII - Le corona',
        description: "Le corona m'a tué",
        level: 1,
        imageName: 'ff8-corona.jpg',
        isFusion: 0,
        lore: "Un boss de FF8 présent vers la fin du jeu m'a tué. Ca arrive. Quelle était la probabilité par contre qu'il me tue avec une attaque nommée Corona alors que nous étions en pleine pandémie de Coronavirus, ça c'est la bonne question.",
      },
      {
        id: 81,
        name: 'FFIX - Le meilleur jeu du monde',
        description: "C'est 100% objectif",
        level: 4,
        imageName: 'ff9-best-game.jpg',
        isFusion: 0,
        lore: "Final Fantasy IX est mon jeu préféré, c'est un fait que j'ai assez répété, et donc tout à fait objectivement, il est le meilleur jeu du monde.",
      },
      {
        id: 82,
        name: 'FFX - Le mec mort intuable',
        description: "Alors qu'il y en avait des opportunités",
        level: 2,
        imageName: 'ff10-seymour.jpg',
        isFusion: 0,
        lore: 'On connait dans les RPGs des boss qui reviennent plusieurs fois, ou qui ressucitent. FFX utilise un peu trop ce principe avec le méchant du jeu qui revient à la charge plusieurs fois (mais vous êtes les héros, les élus, donc vous gagnez forcément ...',
      },
      {
        id: 83,
        name: 'FFT0 - La 2eme bonne surprise',
        description: 'Cater, top tier',
        level: 2,
        imageName: 'fft0-cater.jpg',
        isFusion: 0,
        lore: "Final Fantasy Type-0 est un spin off sorti sur PSP, beaucoup de gens dont moi sommes passés à coté, mais mon dieu qu'il est cool. Et un des personnages, Cater, est complétement broken.",
      },
      {
        id: 84,
        name: 'FFVIICC - Zack, le héros',
        description: "C'est pas des larmes, c'est la pluie",
        level: 3,
        imageName: 'ff7cc-zack.jpg',
        isFusion: 0,
        lore: "J'avais déjà fait Crisis Core : Final Fantasy VII, j'avais déjà été touché par sa fin, et le refaire n'a pas manqué. Zack est un véritable héros, un personnage incroyable, et surement l'un de mes personnages jouables préférés tout jeu confon...",
      },
      {
        id: 85,
        name: 'FFXII - Le système de gambit',
        description: "C'est encore mieux quand on ne fait rien",
        level: 4,
        imageName: 'ff12-manette.jpg',
        isFusion: 0,
        lore: "Final Fantasy XII propose un gameplay particulier qui fait qu'on l'aime ou on le déteste. Ce système automatise les actions du joueur, si bien que théoriquement, pendant les combats, on peut poser la manette.",
      },
      {
        id: 86,
        name: 'FFXIII - Le lancer de mog',
        description: 'Ça vole bien ces merdes',
        level: 2,
        imageName: 'ff13-mog.jpg',
        isFusion: 0,
        lore: "Je ne suis pas un grand fan de la trilogie FFXIII, mais la meilleure fonctionnalité aura été celle de lancer un mog pour aller chercher des objets. C'était très drole. Désolé petit mog.",
      },
      {
        id: 87,
        name: 'FFXV - Le jeu en kit',
        description: 'Un film, un animé, un jeu, 5 DLCs',
        level: 3,
        imageName: 'ff15-kit.jpg',
        isFusion: 0,
        lore: "Final Fantasy XV est un jeu cross media et avec des DLCs, si bien que pour vivre l'expérience entière de cette oeuvre, il faut jouer à un jeu + faire des DLCs + regarder un film + regarder un animé. Le jeu est sponsorisé par Ikea.",
      },
      {
        id: 88,
        name: 'Le marathon',
        description: "1 an et demi, c'est long",
        level: 4,
        imageName: 'ff-marathon.jpg',
        isFusion: 1,
        lore: "Le projet de faire tous les Final Fantasy aura été une aventure d'un an et demi épuisante, mais c'est le principe d'un marathon, n'est ce pas ?",
      },
      {
        id: 89,
        name: 'La culotte de Moxi',
        description: 'Le seul clickbait de la chaine',
        level: 1,
        imageName: 'borderlands-moxi.jpg',
        isFusion: 0,
        lore: "Un des tutos pour Borderlands 2 que j'ai fait, l'une des vidéos de ma chaine la plus vue, permettait de voir sous la jupe de Moxxi. Conscient du potentiel de clickbait, ça n'a pas loupé. Bande de petits vicieux.",
      },
      {
        id: 90,
        name: 'Le buzz',
        description: 'Likez pour des clefs en or',
        level: 2,
        imageName: 'borderlands-golden-key.jpg',
        isFusion: 0,
        lore: "Borderlands 2 a ajouté un système de clef en or. Au début les gens ne savaient pas où en trouver, si bien que je les partageais sur Twitter. Cela n'a pas manqué et il y a eu un petit stonks de followers.",
      },
      {
        id: 91,
        name: 'Etalon du cul',
        description: 'Le plus beau de tous les poneys',
        level: 1,
        imageName: 'borderlands-etalon-du-cul.jpg',
        isFusion: 0,
        lore: "Fan de poney, j'ai beaucoup apprécié étalon du cul, cet animal splendide. Voilà c'est tout.",
      },
      {
        id: 92,
        name: 'Le destructeur',
        description: "C'est honteux",
        level: 1,
        imageName: 'borderlands-destructor.jpg',
        isFusion: 0,
        lore: "Boss final de Borderlands 1, il est une honte pour ce premier opus et pour la saga. Il ne mérite pas d'exister.",
      },
      {
        id: 93,
        name: 'Le mal aimé',
        description: 'Avec Gortys, le plus rigolo des robots',
        level: 1,
        imageName: 'borderlands-gortys.jpg',
        isFusion: 0,
        lore: 'Très peu de gens ont joué à Tales from the Borderlands alors que le jeu est canon. Ce jeu introduit pourtant Gortys, un petit robot tout mignon et rigolo. Coeur sur lui.',
      },
      {
        id: 94,
        name: 'La meilleure Warframe',
        description: 'Eternel incompris, 100% objectif',
        level: 3,
        imageName: 'warframe-limbo.jpg',
        isFusion: 0,
        lore: "Warframe possède plusieurs dizaines de Warframe jouable, si bien qu'évidemment, chacun a sa petite Warframe préférée. Personnellement, c'est Limbo, mais les gens ne comprennent pas son gameplay et beaucoup de gens ne l'aiment pas. Allez savoir pourq...",
      },
      {
        id: 95,
        name: 'Farm du Prime Access',
        description: 'Le rendez vous trimestriel',
        level: 1,
        imageName: 'warframe-prime-access.jpg',
        isFusion: 0,
        lore: 'Tous les 3 mois, une nouvelle Warframe Prime sort avec son armement lui aussi Prime, et donc tous les trois mois, le farm de ce contenu est organisé.',
      },
      {
        id: 96,
        name: 'We all lift together',
        description: "And we're all adrift together, togetheeeeer",
        level: 2,
        imageName: 'warframe-fortuna.jpg',
        isFusion: 0,
        lore: "Musique d'intro de Fortuna, elle est s'y entrainante qu'elle est entrée dans les playlists de plusieurs joueurs. Un banger comme disent les jeunes.",
      },
      {
        id: 97,
        name: 'Mordax',
        description: "L'incarnation féline du simili de Dramo",
        level: 2,
        imageName: 'warframe-mordax.jpg',
        isFusion: 1,
        lore: 'Mordax est mon Kavat dans le jeu. Il est l\'habile mélange entre Dramo et le concept de Simili de Kingdom Hearts. En effet, les Similis sont "une autre forme" des gens (pour résumer), ils sont nommés via un anagramme du nom de base avec un X à l\'inté...',
      },
      {
        id: 98,
        name: 'On ne les compte plus',
        description: "Ca va, c'est pas tant que ça",
        level: 1,
        imageName: 'warframe-time.jpg',
        isFusion: 0,
        lore: "Depuis 2013, j'ai continué de jouer à Warframe, ce qui fait que j'ai quelques heures de jeux. Photo non contractuelle, les 4000 ont été dépassées.",
      },
      {
        id: 99,
        name: 'GuideFR',
        description: 'Le caméraman des Progress',
        level: 1,
        imageName: 'warframe-guidefr.jpg',
        isFusion: 0,
        lore: "GuideFR est mon reroll qui m'a permis de filmer les différentes quêtes du jeu quand elles n'étaient pas rejouables. Ca m'a aussi permis de revoir le jeu du point de vue d'un nouveau joueur. Si vous regardez un Progress, vous verrez donc ce compte là.",
      },
      {
        id: 100,
        name: 'Le nemesis',
        description: "Slowrunner dans l'ame",
        level: 1,
        imageName: 'warframe-whiteangel.jpg',
        isFusion: 0,
        lore: "VVhiteAngel est un Youtuber/Streamer français sur Warframe. Il est le plus connu en France. Problème : Je n'aime pas son contenu parce qu'il prend 40 minutes à expliquer des choses qu'on peut résumer en 10min. C'est donc devenu un peu un running gag. Sa photo est d'ailleurs un avatar qu'il a sur un forum de création d'entreprise pour femme ou un truc dans le genre. Voilà.",
      },
      {
        id: 101,
        name: 'Fxdpt',
        description: 'Le schweppes tonic est sa kryptonite',
        level: 2,
        imageName: 'fxdpt.jpg',
        isFusion: 0,
        lore: 'Fx a un souci cardiaque et dans le Schweppes Tonic il y a de la quinine qui est un excitant',
      },
      {
        id: 102,
        name: 'Dron',
        description: 'Auteur et parolier de rap aux gouts douteux',
        level: 2,
        imageName: 'dron.jpg',
        isFusion: 0,
        lore: "Dron aime le rap FR et sortir des punchlines ou faire des citations de rappeur, mais en terme de jeu vidéo il a apprécié des jeux ne faisant pas l'unanimité dirons nous",
      },
      {
        id: 103,
        name: 'Tribal',
        description: "Il adore s'envoyer en l'air",
        level: 2,
        imageName: 'tribal.jpg',
        isFusion: 0,
        lore: "Tribal (ou encore Swordcrash) est fan d'aviation, voilà tout",
      },
      {
        id: 104,
        name: 'Devola et Popola',
        description: 'Waifu material, debat parallèle',
        level: 3,
        imageName: 'devolapopola.jpg',
        isFusion: 0,
        lore: "2 waifus incroyables de Nier Replicant et Nier Automata. Ici à la rédac', on aime beaucoup",
      },
      {
        id: 105,
        name: 'Yuito & Kasane',
        description: 'Héros unis par les fils rouges',
        level: 2,
        imageName: 'scarlet.jpg',
        isFusion: 0,
        lore: "Le fil rouge est leur pouvoir commun et ils font parti des rares personnes capable d'utiliser ce pouvoir",
      },
      {
        id: 106,
        name: 'Arashi',
        description: "Rapide comme l'éclair, fainéante comme jamais",
        level: 4,
        imageName: 'arashi.jpg',
        isFusion: 0,
        lore: 'Petit traitement de faveur parce que je la trouve trop stylée. Son pouvoir est une rapidité extrême, mais elle aime par dessus tout ne rien faire, comme moi',
      },
      {
        id: 107,
        name: 'Bastion',
        description:
          "Le premier chef d'oeuvre avec un narrateur à la voix suave",
        level: 2,
        imageName: 'bastion.jpg',
        isFusion: 0,
        lore: 'Un petit jeu indé incroyable avec un narrateur exceptionnel',
      },
      {
        id: 108,
        name: 'Transistor',
        description: "Meilleur jeu indé de l'année 2014 à la BO incroyable",
        level: 4,
        imageName: 'transistor.jpg',
        isFusion: 0,
        lore: "Le premier jeu indé qui m'a mis sur le cul tellement il est exceptionnel avec une BO incroyable de Darren Korb",
      },
      {
        id: 109,
        name: 'Pyre',
        description: 'Mix entre du hand-ball et réfugié syrien simulator',
        level: 1,
        imageName: 'pyre.jpg',
        isFusion: 0,
        lore: 'Un jeu avec beaucoup de blabla, un gameplay avec un ballon ressemblant au handball, où le but est de fuir la zone où nos héros sont, une zone où tous les rebuts de la société se trouve',
      },
      {
        id: 110,
        name: 'Hades',
        description: 'Le jeu indépendant qui a conquis le monde',
        level: 3,
        imageName: 'hades.jpg',
        isFusion: 0,
        lore: 'Indé primé moulte fois, le plus gros succès de Supergiant Games',
      },
      {
        id: 111,
        name: 'Supergiant Games',
        description: "L'un des meilleurs studios indé",
        level: 3,
        imageName: 'supergiant.jpg',
        isFusion: 1,
        lore: 'Un studio de développement qui a produit uniquement des dingueries, avec une politique non toxique <3',
      },
      {
        id: 112,
        name: 'Remember Me',
        description:
          "N'a pas eu le succès escompté mais un véritable chef d'oeuvre",
        level: 2,
        imageName: 'remember.jpg',
        isFusion: 0,
        lore: "Un jeu incroyable, mélangeant Beat'em'all, plate-forme et réflexion avec une histoire très cool, mais qui ne s'est pas vendu autant qu'il aurait mérité",
      },
      {
        id: 113,
        name: 'Life is Strange',
        description:
          "La vie est bizarre, surtout quand t'as des super-pouvoirs",
        level: 2,
        imageName: 'lis.jpg',
        isFusion: 0,
        lore: 'Jeu narratif qui a un peu redéfini le genre, chaque jeu est une nouvelle histoire avec des capacités particulières (le 2 est nul)',
      },
      {
        id: 114,
        name: 'Vampyr',
        description: 'Etre médecin et vampire, ça aide pour les prises de sang',
        level: 1,
        imageName: 'vampyr.jpg',
        isFusion: 0,
        lore: 'Jeu dans un 18e siècle victorien, où on joue un médecin vampire, dans une ville infectée par la Peste',
      },
      {
        id: 115,
        name: 'Dontnod Studio',
        description: 'Parce que la FRANCE fait aussi de bons jeux',
        level: 2,
        imageName: 'dontnod.jpg',
        isFusion: 1,
        lore: 'Studio Parisien qui a fait des jeux très cools et variés',
      },
      {
        id: 116,
        name: 'Ori',
        description: 'Un métroidvania magnifique aux controles très agréables',
        level: 3,
        imageName: 'ori.jpg',
        isFusion: 0,
        lore: "Deux jeux de plate-forme sublimes, à la bande son incroyable et au gameplay d'une fluidité exceptionnelle",
      },
      {
        id: 117,
        name: 'Horizon',
        description:
          "A quel moment appeler son personnage principal 'alliage' est une bonne idée ?",
        level: 4,
        imageName: 'horizon.jpg',
        isFusion: 0,
        lore: "Le personnage principal s'appelle Aloy, et Alloy en anglais ça veut dire alliage. Comme celui des robots du jeu. c tro mal1",
      },
      {
        id: 118,
        name: 'Nier',
        description: "L'un est bon, l'autre est surcoté",
        level: 2,
        imageName: 'nier.jpg',
        isFusion: 0,
        lore: "J'ai découvert la licence avec Nier Automata où les gens se branlent sur l'histoire que je trouve claqué, le jeu est soit disant philosophique alors que bof, y'avait bien mieux à faire, mais au moins Nier Replicant (premier du nom ou son remake peu i...",
      },
      {
        id: 119,
        name: 'Mass Effect',
        description: "Surcoté, une étoile télérama et encore c'est généreux",
        level: 1,
        imageName: 'masseffect.jpg',
        isFusion: 0,
        lore: "Je vous ai déjà dit que j'avais pas aimé ?",
      },
      {
        id: 120,
        name: 'Inmost',
        description:
          'Une pépite au pixel art sublimé par la lumière avec une histoire avec un theme dur',
        level: 3,
        imageName: 'inmost.jpg',
        isFusion: 0,
        lore: "Petit jeu sans prétention qui est incroyablement beau avec son pixel art soigné et surtout ses lumières, et qui parle d'un sujet pas très cool mais bon je vais rien dire sinon jvais vous spoil. Faites le jeu <3",
      },
      {
        id: 121,
        name: 'Cave Story',
        description:
          'Un petit jeu fait par un Japonais solo qui a fini par être un classique',
        level: 1,
        imageName: 'cave.jpg',
        isFusion: 0,
        lore: 'Ce jeu est sorti sur PC en 2004, créé par un mec solo en 5 ans. Il est gratuit en plus. Le jeu a ensuite été porté par son créateur et une autre personne pour sortir le jeu sur le WiiWare en 2010, puis le jeu a été refait en mieux et est sorti en...',
      },
      {
        id: 122,
        name: 'The Last of Us',
        description:
          'Le jeu qui ne suit pas les codes Holywoodiens et ça plait pas aux joueurs',
        level: 3,
        imageName: 'tlou.jpg',
        isFusion: 0,
        lore: "On a toujours des films ou des jeux avec les mêmes développement d'histoire et de personnage, avec la même happy ending, alors quand les choses changent un peu, forcément les gens sont surpris et ralent... La peur du changement que voulez vous",
      },
      {
        id: 123,
        name: 'Hellblade',
        description: 'Entendre des voix pour une immersion incroyable',
        level: 2,
        imageName: 'hellblade.jpg',
        isFusion: 0,
        lore: 'Senua, le personnage principal, a des petits problèmes dans sa tête, et le jeu retranscrit ça de plusieurs manières et notamment avec de multiples murmures très immersifs',
      },
      {
        id: 124,
        name: 'Electronic Super Joy',
        description:
          "Un jeu où le pape vole ton cul est forcément exceptionnel (attention à l'épilepsie)",
        level: 1,
        imageName: 'esj.jpg',
        isFusion: 0,
        lore: "La description, c'est littéralement la base de l'histoire du premier jeu. Le jeu a beaucoup d'effets visuels, d'où le warning",
      },
      {
        id: 125,
        name: 'Hollow Knight',
        description: "Silksong annoncé incessament sous peu, c'est sûr",
        level: 3,
        imageName: 'hollow.jpg',
        isFusion: 0,
        lore: "Silksong, la suite du premier jeu, est attendu depuis très longtemps et chaque conf est le moment parfait pour espérer l'annonce",
      },
      {
        id: 126,
        name: 'Celeste',
        description:
          "Quand tu combats la dépression en t'enfonçant dans le tryhard",
        level: 2,
        imageName: 'celeste.jpg',
        isFusion: 0,
        lore: 'Le jeu représente le combat contre la dépression (escalader la montagne, affronter ses démons, tout ça), mais avec sa difficulté il faut bien tryhard et si vous êtes pas persévérants, potentiellement vous déprimer',
      },
      {
        id: 127,
        name: 'Gris',
        description:
          "Un jeu indé qu'Ashara a trouvé beau, c'est vous dire la qualité du jeu",
        level: 2,
        imageName: 'gris.jpg',
        isFusion: 0,
        lore: "Ashara est quelqu'un d'exigeant. Alors quand un jeu indé le rend aussi enthousiaste, c'est que le jeu est exceptionnel",
      },
      {
        id: 128,
        name: 'A Hat in time',
        description: 'Mario mais en mieux, et tout mignon',
        level: 1,
        imageName: 'hat.jpg',
        isFusion: 0,
        lore: "Jeu de plate-forme très agréable, tout mignon, avec plusieurs petites histoires par monde qui change du sauvetage de princesse. L'illustration c'est un screenshot de mon personnage, il est meugnon hein ?",
      },
      {
        id: 129,
        name: 'Spyro',
        description: 'Le dragon le plus mignon du jeu vidéo',
        level: 2,
        imageName: 'spyro.jpg',
        isFusion: 0,
        lore: 'Classique parmi les classiques, je ne pense pas devoir vous le présenter !',
      },
      {
        id: 130,
        name: 'Crash Bandicoot',
        description: "Le bandicoot le plus barré de l'univers",
        level: 2,
        imageName: 'crash.jpg',
        isFusion: 0,
        lore: "Crash est le bandicoot le plus barré de l'univers mais en même temps, il y en a pas des masses vu que cette race est issue des experimentations de Docteur Cortex",
      },
      {
        id: 131,
        name: 'Read Dead Redemption',
        description: "Des cowboys qui s'attirent des ennuis",
        level: 3,
        imageName: 'rdr.jpg',
        isFusion: 0,
        lore: "Jeu de cowboy par excellence, tout commence bien aux débuts des jeux quand soudain : c'est la merde",
      },
      {
        id: 132,
        name: 'Dragon Quest VIII',
        description: "A la poursuite d'un clown et d'un sceptre magique",
        level: 3,
        imageName: 'dq8.jpg',
        isFusion: 0,
        lore: "Le méchant de l'histoire est Dhoulmagus, un fou du roi, et il possède un sceptre maléfique qui nous obligera à parcourir le monde et ses dangers !",
      },
      {
        id: 133,
        name: 'Dragon Quest XI',
        description:
          "Le jeu de schrodinger : Je l'ai fini mais je l'ai pas fini",
        level: 3,
        imageName: 'dq11.jpg',
        isFusion: 0,
        lore: "J'ai fini l'histoire normale du jeu, à la fin de celle ci.... En fait il y a une suite ! Et je n'ai jamais eu/pris le temps de la faire",
      },
      {
        id: 134,
        name: 'Ruiner',
        description: 'Violence and Cyberpunk intensifies',
        level: 1,
        imageName: 'ruiner.jpg',
        isFusion: 0,
        lore: "Bon bah... C'est juste un jeu ultra violent dans un univers cyberpunk quoi",
      },
      {
        id: 135,
        name: 'Detroit Become Human',
        description: "Le sauveur, l'android au grand coeur, et le connard",
        level: 1,
        imageName: 'detroit.jpg',
        isFusion: 0,
        lore: "On joue 3 personnages, un robot qui veut sauver son espèce, une autre qui protège une petite fille, et un connard (robot aussi) qui est du coté des flics et de l'oppression",
      },
      {
        id: 136,
        name: 'The order 1886',
        description:
          "Un jeu très cool qui n'aura jamais de suite, c'est triste",
        level: 1,
        imageName: 'order.jpg',
        isFusion: 0,
        lore: "Le jeu est sorti au début de l'air PS4, il était très cool mais forcément bien moins avancé et connu que les jeux de fin de génération. Il était pourtant très sympa dans un univers original",
      },
      {
        id: 137,
        name: 'Prey',
        description:
          'Une masterclass du jeu vidéo, avec un DLC innovant, qui enseigne que les gros sont méchants',
        level: 2,
        imageName: 'prey.jpg',
        isFusion: 0,
        lore: "Jeu qui nous a enseigné que chaque personnage gros dans un jeu vidéo est un méchant, malgré tout c'est un jeu incroyable, mais je vous conseille encore plus son DLC qui est exceptionnel (Deathloop mais en bien finalement)",
      },
      {
        id: 138,
        name: 'Spec Ops',
        description: "C'était pas ma guerre",
        level: 1,
        imageName: 'specops.jpg',
        isFusion: 0,
        lore: 'Un jeu de guerre où on incarne un soldat et qui retranscrit, pour une fois, les traumatismes que cela peut avoir',
      },
      {
        id: 139,
        name: 'Crysis',
        description: "C'était mieux avant",
        level: 1,
        imageName: 'crysis.jpg',
        isFusion: 0,
        lore: "Typiquement le genre de jeux qui ne s'est pas bonifié avec le temps. Les deux premiers sont très bien, c'est tout ce que je dirais",
      },
      {
        id: 140,
        name: 'Undertale',
        description: 'Surcoté, rip Toriel',
        level: 1,
        imageName: 'undertale.jpg',
        isFusion: 0,
        lore: "Jeu apprécié par une bonne partie des joueurs mais que j'ai trouvé pas fou sur tous les points (à part Mettaton). Ah et j'ai tué personne dans ma run à part notre mère adoptive, ne suis je pas un enfant modèle ?",
      },
      {
        id: 141,
        name: 'Gran Turismo 7',
        description: 'ELLE EST BELLE MA SUBARU HEIN ?',
        level: 2,
        imageName: 'gt7.jpg',
        isFusion: 0,
        lore: 'La réponse à la question de la description est : oui',
      },
      {
        id: 142,
        name: 'Lost Ark',
        description: 'Je déteste les MMOs, mais je suis conquis',
        level: 3,
        imageName: 'lostark.jpg',
        isFusion: 0,
        lore: 'Je ne suis pas un grand fan de MMO, loin de là, mais il y a des exceptions à tout',
      },
    ],
  });

  [
    { fusionId: 12, dependencyIds: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
    { fusionId: 63, dependencyIds: [2, 39] },
    { fusionId: 72, dependencyIds: [65, 66, 67, 68, 69, 70, 71] },
    {
      fusionId: 88,
      dependencyIds: [
        73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
      ],
    },
    { fusionId: 97, dependencyIds: [21, 40, 68] },
    { fusionId: 111, dependencyIds: [107, 108, 109, 110] },
    { fusionId: 115, dependencyIds: [112, 113, 114] },
  ].forEach(
    async ({ fusionId, dependencyIds }) =>
      await prisma.cardType.update({
        where: { id: fusionId },
        data: {
          fusionDependencies: {
            connect: dependencyIds.map((id) => ({ id })),
          },
        },
      })
  );

  await prisma.config.createMany({
    data: [
      {
        id: 1,
        name: 'DROP_CHANCES',
        value: { '1': 50, '2': 30, '3': 15, '4': 5 },
      },
      {
        id: 2,
        name: 'LEVELS',
        value: {
          '1': 0,
          '2': 1500,
          '3': 2500,
          '4': 5000,
          '5': 7500,
          '6': 10000,
          '7': 13300,
          '8': 16600,
          '9': 20000,
          '10': 23300,
          '11': 26600,
          '12': 30000,
          '13': 33300,
          '14': 36600,
          '15': 40000,
          '16': 43300,
          '17': 46600,
          '18': 50000,
          '19': 55000,
          '20': 60000,
          '21': 65000,
          '22': 70000,
          '23': 75000,
          '24': 80000,
          '25': 85000,
          '26': 90000,
          '27': 95000,
          '28': 100000,
          '29': 105000,
          '30': 110000,
          '31': 115000,
          '32': 120000,
          '33': 125000,
          '34': 130000,
          '35': 135000,
          '36': 140000,
          '37': 145000,
          '38': 150000,
          '39': 155000,
          '40': 160000,
        },
      },
      { id: 3, name: 'PRICE', value: { price: 1000 } },
      {
        id: 4,
        name: 'TWITCH_REWARD',
        value: { points: 2500, rewardName: 'Points de gacha (Discord)' },
      },
      { id: 5, name: 'SELL', value: { gold: 300, basic: 100 } },
      { id: 6, name: 'CARD_XP', value: { gold: 500, basic: 100 } },
    ],
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
